# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d062a19d9aa93f78b17ce8b2b85e192d80b6343f789884b5f451ef3c6be828c076e3d699dc9375d41e8fdc8df6d99f6aa28ea029eaefc2c8131eb463d742d78c

test:
  secret_key_base: 6659ffcfa5f8bd0992f977b525906ae02048e3e639a2e492a6e95e0679425c015c02c3a85952364b9ca90a40a20833598804e3ac9f83b89a1a0c456ea0665902

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
